// Optional: install Playwright separately, run the dev server, then run this file.
// TEST_BASE_URL selects a server other than the default http://127.0.0.1:5173.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {generateReply} from '../src/chat.ts';
import {labs} from '../src/data.ts';

const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH||'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
const baseUrl=process.env.TEST_BASE_URL||'http://127.0.0.1:5173/';
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
const errors=[],requests=[];
page.on('pageerror',error=>errors.push(error.message));
// Verify the chat request/response path without making a paid external API call.
await page.route('**/api/chat',async route=>{
 const body=route.request().postDataJSON();requests.push(body);
 await route.fulfill({json:{text:await generateReply(body.question,body.context)}});
});
const sec=labs.find(l=>l.professor==='구형준'),hit=labs.find(l=>l.professor==='최형기');
async function stored(){return page.evaluate(()=>JSON.parse(localStorage.getItem('lab-map-v1')));}
async function noOverlay(locator,dock){
 await locator.scrollIntoViewIfNeeded();
 const rect=await locator.boundingBox(),bar=await dock.boundingBox();
 assert.ok(rect&&bar);
 const overlaps=rect.x<bar.x+bar.width&&rect.x+rect.width>bar.x&&rect.y<bar.y+bar.height&&rect.y+rect.height>bar.y;
 assert.equal(overlaps,false,'selection dock obscures content or chat input');
}
try{
 await page.goto(baseUrl);
 await page.getByRole('button',{name:'이 관심 분야를 더 구체적으로 나누면 어떻게 돼? ↗'}).click();
 await page.getByText('아직 관심 분야가 입력되지 않았습니다.',{exact:false}).waitFor();
 await page.getByRole('textbox',{name:'어떤 분야가 궁금한가요?'}).fill('보안 구형준 최형기');
 await page.getByRole('button',{name:'후보 찾기 →'}).click();
 assert.equal(await page.locator('.compact-candidates > article').count(),4);
 assert.equal(await page.locator('.compact-candidates > article details[open]').count(),0);
 assert.ok((await page.locator('.lab .tags').evaluateAll(els=>els.every(el=>el.children.length<=3))));
 const compare=page.getByRole('button',{name:'선택한 연구실 비교하기 →',exact:true});
 assert.equal(await compare.isDisabled(),true);
 await page.getByRole('button',{name:sec.name+' 후보에 담기',exact:true}).click();
 assert.equal(await compare.isDisabled(),true);
 assert.equal((await stored()).selected.length,1);
 assert.deepEqual((await stored()).reasons,{});
 await page.getByRole('textbox',{name:sec.name+' · 개인적인 선택 이유',exact:true}).fill('RAG 보안 문제를 직접 알아보고 싶어서');
 await page.getByRole('button',{name:hit.name+' 후보에 담기',exact:true}).click();
 assert.equal(await compare.isEnabled(),true);
 assert.equal(await page.getByRole('button',{name:/후보에 담기$/}).first().isDisabled(),true);
 await page.getByRole('button',{name:/관련 후보 더 보기/}).click();
 assert.ok(await page.locator('.compact-candidates > article').count()>4);
 assert.equal((await stored()).selected.length,2);
 await page.getByRole('button',{name:hit.name+' 선택 해제',exact:true}).click();
 assert.equal(await compare.isDisabled(),true);
 await page.getByRole('button',{name:hit.name+' 후보에 담기',exact:true}).click();
 const dock=page.getByRole('region',{name:'연구실 선택 상태'});
 await noOverlay(page.getByRole('textbox',{name:hit.name+' · 개인적인 선택 이유',exact:true}),dock);
 await noOverlay(page.getByRole('textbox',{name:'도우미에게 질문'}),dock);
 await compare.click();
 assert.equal(await page.locator('.lab-comparison thead th').count(),3);
 assert.equal(await page.locator('.lab-comparison tbody tr').count(),7);
 await page.locator('.lab-comparison').getByText('강의코드 ESW5042-41',{exact:true}).waitFor();
 await page.locator('.lab-comparison').getByText('강의코드 SWE3025-41',{exact:true}).waitFor();
 assert.equal(await page.locator('.comparison-details > section > details[open]').count(),0);
 const secDetail=page.getByText(sec.name+' 상세 정보',{exact:true});
 await secDetail.click();
 await page.getByText('강의 시간: 수[DD]13:30-14:45 【1.5h(ON)+1.5h(OFF)】',{exact:true}).waitFor();
 assert.ok(await page.locator('.comparison-details a[href="https://secai.skku.edu/publications/"]').count()>0);
 await page.getByRole('button',{name:'관심 학습 주제 저장',exact:true}).first().click();
 await secDetail.click();
 assert.equal(await page.getByRole('button',{name:'이 연구 주제 체험하기 →',exact:true}).count(),1);
 await page.getByRole('button',{name:'선택한 두 연구실의 가장 큰 차이는 뭐야? ↗'}).click();
 await page.locator('.bubble.assistant').filter({hasText:'보유한 연구 방법과 문제의 차이'}).waitFor();
 await page.getByRole('button',{name:'이전 화면',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:sec.name+' · 개인적인 선택 이유',exact:true}).inputValue(),'RAG 보안 문제를 직접 알아보고 싶어서');
 await compare.click();
 await page.getByRole('button',{name:'이 연구 주제 체험하기 →',exact:true}).click();
 await page.getByRole('heading',{name:'AI가 잘못된 자료를 읽으면 어떻게 될까?',exact:true}).waitFor();
 const save=page.getByRole('button',{name:'체험 저장하고 내 탐색 정리하기 →',exact:true});
 assert.equal(await save.isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'3. 방어',exact:true}).isDisabled(),true);
 assert.equal((await stored()).experienceSelection.labId,sec.id);
 assert.equal(await page.locator('.research-connection').getAttribute('open'),null);
 await page.getByRole('button',{name:'이 체험을 직접 구현하려면 무엇부터 공부해야 해? ↗'}).click();
 await page.locator('.bubble.assistant').filter({hasText:'아직 실행한 체험 단계가 없습니다.'}).waitFor();
 await page.getByRole('button',{name:'정상 단계 실행',exact:true}).click();
 await page.locator('.rag-answer').getByText('대출 기간은 14일입니다.',{exact:true}).waitFor();
 assert.equal(await page.locator('.documents-scroll .doc').count(),5);
 await page.getByRole('button',{name:'2. 공격',exact:true}).click();
 assert.equal((await stored()).rag.executed.length,1);
 assert.equal(await page.locator('.rag-answer').innerText(),'대출 기간은 14일입니다.');
 await page.getByRole('button',{name:'공격 단계 실행',exact:true}).click();
 await page.locator('.rag-answer').getByText('대출 기간은 30일입니다.',{exact:true}).waitFor();
 assert.equal(await page.locator('.documents-scroll .doc').count(),8);
 assert.equal(await page.getByText('추가된 문서',{exact:true}).count(),3);
 assert.equal(await page.getByText('필터로 제외됨',{exact:true}).count(),0);
 await page.getByRole('button',{name:'3. 방어',exact:true}).click();
 assert.equal(await save.isDisabled(),true);
 assert.equal(await page.locator('.rag-answer').innerText(),'대출 기간은 30일입니다.');
 await page.getByRole('button',{name:'방어 단계 실행',exact:true}).click();
 await page.locator('.rag-answer').getByText('대출 기간은 14일입니다.',{exact:true}).waitFor();
 assert.equal(await page.getByText('필터로 제외됨',{exact:true}).count(),3);
 await page.getByText('정상 14일 → 공격 30일 → 방어 14일',{exact:true}).waitFor();
 assert.equal(await save.isEnabled(),true);
 assert.equal(await page.locator('.optional-learning > details[open]').count(),0);
 assert.equal(await page.getByRole('button',{name:'예시 체험만 진행하기',exact:true}).count(),0);
 await page.getByRole('textbox',{name:'관찰한 점 한 줄 남기기 선택 입력'}).fill('가짜 문서가 답변을 바꿨고 필터 후 14일로 돌아왔다');
 await save.click(); // Optional learning remains unopened and unselected.
 await page.getByRole('heading',{name:'내 탐색 정리하기',exact:true}).waitFor();
 assert.equal(await page.locator('#opinion, #result-map, #next-action').count(),3);
 assert.equal((await stored()).rag.planSaved,false);
 await page.getByRole('button',{name:'이전 화면',exact:true}).click();
 await page.getByText('더 해보고 싶다면: 4주 심화 프로젝트',{exact:true}).click();
 await page.getByRole('button',{name:'내 준비 계획에 담기',exact:true}).click();
 await page.getByText('직접 구현하기 전에 공부할 것',{exact:true}).click();
 await page.getByText('직접 RAG 만들기',{exact:true}).click();
 await page.getByRole('button',{name:'Python 기초',exact:true}).click();
 await save.click();
 const expNode=page.locator('#result-map summary').filter({hasText:'연구 체험'});
 await expNode.click();
 await page.getByText('공부 항목: Python 기초',{exact:false}).waitFor();
 const personalBefore=(await stored()).reflection;
 await page.getByRole('button',{name:'내 탐색 내용을 바탕으로 다음 공부를 정리해줘. ↗'}).click();
 await page.locator('.bubble.assistant').filter({hasText:'선택한 공부: Python 기초'}).waitFor();
 assert.deepEqual((await stored()).reflection,personalBefore);
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Markdown 다운로드 ↓',exact:true}).click();
 assert.match((await download).suggestedFilename(),/\.md$/);
 await page.reload();
 const restored=await stored();
 assert.equal(restored.version,4);
 assert.deepEqual(restored.rag.executed,['normal','attack','defense']);
 assert.equal(restored.rag.observation,'가짜 문서가 답변을 바꿨고 필터 후 14일로 돌아왔다');
 assert.equal(restored.rag.planSaved,true);assert.deepEqual(restored.rag.studyIds,['python']);
 assert.equal(restored.reasons[sec.id],'RAG 보안 문제를 직접 알아보고 싶어서');
 assert.equal(restored.statuses[2],'완료');assert.equal(restored.messages.length,8);
 assert.equal(requests[0].context.selected.length,0);
 assert.equal(requests[1].context.selected.length,2);
 assert.equal(requests[2].context.experienceSelection.topicId,'rag-poison-defense');
 assert.deepEqual(requests[2].context.rag.executed,[]);
 assert.deepEqual(requests[3].context.rag.executed,['normal','attack','defense']);
 assert.deepEqual(requests[3].context.rag.studyIds,['python']);
 await page.getByRole('button',{name:/01.*관심 연구실 찾기/}).click();
 await page.setViewportSize({width:390,height:844});
 await noOverlay(page.getByRole('textbox',{name:'도우미에게 질문'}),page.getByRole('region',{name:'연구실 선택 상태'}));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'선택한 연구실 비교하기 →',exact:true}).click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'이 연구 주제 체험하기 →',exact:true}).click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'이전 화면',exact:true}).click();
 await page.getByRole('button',{name:'이전 화면',exact:true}).click();
 await page.getByRole('textbox',{name:'어떤 분야가 궁금한가요?'}).fill('자연어처리');
 assert.equal((await stored()).rag.observation,restored.rag.observation);
 assert.equal((await stored()).messages.length,restored.messages.length);
 assert.ok((await stored()).statuses.slice(1).every(s=>s==='재검토 필요'||s==='시작 전'));
 const scarce=await browser.newPage();
 await scarce.goto(baseUrl);await scarce.getByRole('textbox',{name:'어떤 분야가 궁금한가요?'}).fill('구형준');
 await scarce.getByRole('button',{name:'후보 찾기 →'}).click();
 assert.equal(await scarce.locator('.review').innerText(),'비교할 후보가 2개 미만입니다. 두 연구실을 찾을 수 있도록 관심 분야를 수정해 주세요.');
 assert.equal(await scarce.getByRole('button',{name:'선택한 연구실 비교하기 →',exact:true}).isDisabled(),true);
 await scarce.close();
 assert.deepEqual(errors,[]);
 console.log('PASS: two-candidate limit, optional reasons, load more, aligned comparison, lecture codes/details, topic identity, actual three-stage runs, saved notes/learning, chat context/history, page 4 layout, download, desktop/mobile dock and overflow');
}finally{await browser.close();}
