// Optional: npm.cmd install --no-save playwright, then node tests/browser-smoke.mjs
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:5173/');
 await page.getByRole('button',{name:'+ 보안',exact:true}).click();
 await page.getByRole('button',{name:'연구실 후보 찾기 →'}).click();
 await page.getByText('구형준',{exact:true}).waitFor();
 await page.getByRole('button',{name:'관심 후보 선택',exact:true}).first().click();
 await page.getByRole('button',{name:'선택한 연구실 비교하기 →'}).click();
 await page.getByRole('button',{name:'관심 과목 저장',exact:true}).first().click();
 await page.getByRole('button',{name:'교수님 수업과 관련 과목은 어떻게 달라? ↗'}).click();
 await page.getByText('교수님 담당 수업은 누가 가르치는지에 대한 정보이고,',{exact:false}).waitFor();
 await page.getByRole('button',{name:'비교 내용 확인 완료 →'}).click();
 await page.getByRole('button',{name:'분야 열기'}).click();
 for (let i=0;i<7;i++) {
  await page.getByText('연구실이 보는 것',{exact:true}).waitFor();
  if (i===0) await page.getByRole('heading',{name:'AI 보안',exact:true}).waitFor();
  if (i===2) await page.getByRole('button',{name:'이 분야가 더 궁금해요'}).click();
  await page.getByRole('button',{name:/다음 분야|관심 분야 정하기/}).click();
 }
 await page.getByRole('button',{name:'AI 보안',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'체험해보기',exact:true}).isDisabled(),true);
 await page.getByLabel('이 분야가 더 궁금한 이유').fill('평소 기록과 다른 칸을 적는 일이 학부연구생의 기록처럼 느껴졌다');
 await page.getByLabel('랩미팅에서 물어볼 질문').fill('이상 탐지에서는 평소 기록을 어디까지 모아 두나요?');
 await page.getByRole('button',{name:'체험해보기',exact:true}).click();
 await page.getByText('선배가 말합니다.',{exact:false}).waitFor();
 assert.equal(await page.getByText('0.89').count(),0);
 await page.getByRole('button',{name:'시작하기',exact:true}).click();
 await page.locator('article.rag-doc').filter({hasText:'도서관 공지'}).getByRole('button',{name:'근거로 쓴다',exact:true}).click();
 const held=page.locator('article.rag-doc').filter({hasText:'올해는 공지를 확인해 보세요.'});
 await held.getByRole('button',{name:'보류',exact:true}).click();
 await held.getByRole('button',{name:'확인이 더 필요함',exact:true}).click();
 await page.getByRole('button',{name:'다음',exact:true}).click();
 await page.getByRole('button',{name:'문서 6',exact:true}).click();
 await page.getByLabel('내 걸러내기 기준').fill('날짜가 있는 안내와 어긋나면 바로 버리지 않고 보류한다');
 await page.getByRole('button',{name:'다음',exact:true}).click();
 await page.getByRole('button',{name:'방어 방식',exact:true}).click();
 await page.getByLabel('연구실에 물어볼 것').fill('정상 문서를 살리는 기준은 누가 정하나요');
 await page.getByRole('button',{name:'저장하고 돌아가기',exact:true}).click();
 await page.getByText('더 알고 싶은 분야를 하나 고르세요',{exact:false}).waitFor();
 await page.getByRole('button',{name:'이상 탐지 · 궁금',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'증거 분류 기록 점검하기'}).count(),0);
 await page.getByRole('button',{name:'둘러보기 저장',exact:true}).click();
 await page.getByRole('button',{name:'내 선택과 준비 정리하기 →',exact:true}).click();
 await page.getByRole('button',{name:'입문 자료 읽기',exact:true}).click();
 await page.getByRole('button',{name:'준비 기록 저장',exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Markdown 다운로드 ↓'}).click();const file=await download;assert.match(file.suggestedFilename(),/\.md$/);const markdown=await readFile(await file.path(),'utf8');assert.match(markdown,/SecAI Lab · AI 보안 — 검색 결과 묶음 점검/);assert.equal(markdown.includes('0.89'),false);
 await page.reload();
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lab-map-v6')));
 assert.equal(stored.experiments.length,1);assert.equal(stored.experiments[0].focus,'anomaly');assert.equal(stored.selected.length,1);assert.equal(stored.courseIds.length,1);assert.equal(stored.statuses[3],'완료');assert.equal(stored.messages.length,2);
 await page.getByRole('button',{name:'더 탐색하기 →',exact:true}).click();
 await page.getByRole('textbox',{name:'어떤 분야가 궁금한가요?'}).fill('자연어');
 const changed=await page.evaluate(()=>JSON.parse(localStorage.getItem('lab-map-v6')));
 assert.deepEqual(changed.statuses.slice(1),['재검토 필요','재검토 필요','재검토 필요']);assert.equal(changed.experiments.length,1);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'탐색 도우미 닫기'}).click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.equal(await page.getByRole('button',{name:'증거 분류 기록 점검하기'}).count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: browser flow, persistence, chat, field tour, Markdown download, review states, mobile width');
}finally{await browser.close();}
