import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {brand,steps,keywords,experience,questions} from './content.ts';
import {labs,courses,source} from './data.ts';
import {recommend} from './recommend.ts';
import {areas} from './areas.ts';
import {RagReview} from './rag.tsx';
import {clearRag, loadRag, ragMarkdown} from './rag.ts';
import {decode,fresh,invalidate,key,type State} from './store.ts';
import {generateReply} from './chat.ts';
import './style.css';

function App(){
 const [state,setState]=useState<State>(()=>{try{return decode(localStorage.getItem(key));}catch{return fresh();}});
 const [mapView,setMapView]=useState(false),[chatOpen,setChatOpen]=useState(true),[chatInput,setChatInput]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [task,setTask]=useState(0),[areaIndex,setAreaIndex]=useState(0),[curious,setCurious]=useState<string[]>([]),[focus,setFocus]=useState(''),[note,setNote]=useState(''),[ask,setAsk]=useState(''),[ragOpen,setRagOpen]=useState(false);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{setNotice('브라우저 저장 공간을 사용할 수 없습니다. 요약을 다운로드해 기록을 보관하세요.');}},[state]);
 const selected=labs.filter(l=>state.selected.includes(l.id));
 const patch=(p:Partial<State>)=>setState(s=>({...s,...p}));
 function go(step:number){patch({step});setMapView(false);}
 function interest(value:string){setState(s=>({...invalidate(s,0),interest:value,recommended:false,statuses:invalidate(s,0).statuses.map((v,i)=>i===0?'진행 중':v)}));}
 function toggleLab(id:string){setState(s=>{const chosen=s.selected.includes(id);const next=invalidate(s,0);return {...next,selected:chosen?s.selected.filter(x=>x!==id):[...s.selected,id],reasons:{...s.reasons,[id]:s.reasons[id]||recommend(s.interest).find(x=>x.lab.id===id)?.matches.join(', ')||'상세 내용을 보고 관심 후보로 선택'},statuses:next.statuses.map((v,i)=>i===0?'진행 중':v)};});}
 function complete(step:number){setState(s=>({...s,statuses:s.statuses.map((v,i)=>i===step?'완료':v)}));}
 function summary(){return `# ${brand}\n\n관심: ${state.interest||'미입력'}\n수강 경험: ${state.experienceInput||'미입력'}\n더 알고 싶은 내용: ${state.curiosity||'미입력'}\n\n## 과정 상태\n${steps.map((x,i)=>`- ${x.title}: ${state.statuses[i]}`).join('\n')}\n\n## 관심 후보\n${selected.map(l=>`- ${l.name}: ${state.reasons[l.id]||'이유 미입력'}`).join('\n')||'더 탐색하기'}\n\n## 관심 과목\n${courses.filter(c=>state.courseIds.includes(c.id)).map(c=>'- '+c.name).join('\n')||'없음'}\n\n## 저장한 체험\n${state.experiments.map(e=>`- ${e.date} / 더 알고 싶은 분야: ${areas.find(a=>a.id===e.focus)?.name||e.focus}\n  궁금하다고 표시: ${e.visits.filter(v=>v.curious).map(v=>areas.find(a=>a.id===v.areaId)?.name).join(', ')||'없음'}\n  노트: ${e.note}\n  랩미팅 질문: ${e.ask}`).join('\n')||'없음'}\n\n## 생각과 준비\n${reflectionFields.map(([id,label])=>`- ${label}: ${state.reflection[id]||'미작성'}`).join('\n')}\n\n짧은 체험은 적성이나 연구 능력 판정이 아닙니다. ${experience.disclaimer}${ragMarkdown(loadRag())}`;}
 async function send(text:string){if(!text.trim()||busy)return;setBusy(true);setChatOpen(true);setChatInput('');patch({messages:[...state.messages,{role:'user',text}]});try{const reply=await generateReply(text,state);setState(s=>({...s,messages:[...s.messages,{role:'assistant',text:reply}]}));}catch{setState(s=>({...s,messages:[...s.messages,{role:'assistant',text:'응답을 만들지 못했습니다. 다시 시도해 주세요.'}]}));}finally{setBusy(false);}}
 function saveExperiment(){if(!focus||!note.trim()||!ask.trim())return;const visits=areas.map(area=>({areaId:area.id,curious:curious.includes(area.id)||area.id===focus}));setState(s=>({...s,experiments:[...s.experiments,{id:crypto.randomUUID(),date:new Date().toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}),labIds:[...s.selected],note,ask,focus,visits}],statuses:s.statuses.map((v,i)=>i===2?'완료':i===3&&v!=='시작 전'?'재검토 필요':v)}));setNotice('둘러본 분야와 관심 분야를 저장했습니다.');}
 function resetTask(){setTask(0);setAreaIndex(0);setCurious([]);setFocus('');setNote('');setAsk('');setRagOpen(false);clearRag();}
 function snapshot(i:number){return i===0?(state.interest?`${state.interest} · 후보 ${selected.length}개`:'관심 분야부터 시작해요'):i===1?`관심 과목 ${state.courseIds.length}개`:i===2?`저장한 실험 ${state.experiments.length}개`:state.reflection.next||'다음 행동을 정해 보세요';}
 return <>
  <header><div className="brand"><span className="brand-icon">⌘</span><div>{brand}<small>관심에서 시작하는 연구의 첫걸음</small></div><span className="badge">DEMO</span></div><div className="header-actions"><button onClick={()=>setMapView(!mapView)} className={mapView?'primary':''}>나의 탐색 지도</button><button onClick={()=>setChatOpen(!chatOpen)}>탐색 도우미 {chatOpen?'닫기':'열기'}</button></div></header>
  <nav aria-label="탐색 과정">{steps.map((item,i)=><button key={item.title} className={state.step===i&&!mapView?'step active':'step'} onClick={()=>go(i)}><span className="step-number">0{i+1}</span><span><strong>{item.title}</strong><small>{state.statuses[i]} · {snapshot(i)}</small></span></button>)}</nav>
  <div className={'layout '+(!chatOpen?'chat-closed':'')}><main>
   <div className="notice" role="status">{notice||'입력과 기록은 이 브라우저에 자동 저장됩니다. 체험은 연구실 분야를 둘러보는 예시입니다.'}</div>
   {mapView?<><div className="page-heading"><span className="eyebrow">MY EXPLORATION</span><h1>나의 탐색 지도</h1><p>지금까지의 선택과 생각을 연결해 보세요.</p></div><div className="map-cards">{steps.map((item,i)=><article key={item.title}><span className="eyebrow">0{i+1} · {state.statuses[i]}</span><h2>{item.title}</h2><p>{snapshot(i)}</p>{i===0&&selected.map(l=><p key={l.id}>{l.name} — {state.reasons[l.id]||'이유 미작성'}</p>)}{i===2&&<p>{state.reflection.interesting||'체험 후 생각을 정리하면 여기에 표시됩니다.'}</p>}{i===3&&<p>{state.reflection.reason||'관심이 달라진 이유 또는 아직 판단하지 못한 점을 기록해 보세요.'}</p>}<button onClick={()=>go(i)}>기록 살펴보기 →</button></article>)}</div></>:<>
   <div className="page-heading"><span className="eyebrow">STEP 0{state.step+1} / 04</span><h1>{steps[state.step].title}</h1><p>{steps[state.step].description}</p></div>
   {state.statuses[state.step]==='재검토 필요'&&<div className="review">앞 과정의 관심 또는 후보가 바뀌었습니다. 이전 기록은 보존되어 있으며 다시 확인해 주세요.</div>}
   {state.step===0&&<><section><label className="field">어떤 분야가 궁금한가요?<textarea placeholder="예: 보안 연구실이 인공지능과 딥페이크를 어떻게 같이 보는지 궁금해요." value={state.interest} onChange={e=>interest(e.target.value)}/></label><div className="chips">{keywords.map(k=><button key={k} onClick={()=>interest(state.interest?state.interest+', '+k:k)}>+ {k}</button>)}</div><details><summary>수강 경험과 궁금한 점도 알려주기 <span>선택</span></summary><label className="field">수강·과제 경험<input value={state.experienceInput} onChange={e=>patch({experienceInput:e.target.value})}/></label><label className="field">더 알고 싶은 내용<input value={state.curiosity} onChange={e=>patch({curiosity:e.target.value})}/></label></details><button className="primary" disabled={!state.interest.trim()} onClick={()=>patch({recommended:true})}>{steps[0].button} →</button></section>
   {state.recommended&&<><div className="section-title"><h2>관심과 연결되는 연구실</h2><span>태그 일치 기준</span></div>{recommend(state.interest).length===0?<section className="empty">일치하는 연구실이 없습니다. ‘보안’, ‘딥페이크’, ‘자연어’처럼 관심을 조금 더 구체화해 보세요.</section>:<div className="lab-grid">{recommend(state.interest).map(({lab,matches})=><article className={state.selected.includes(lab.id)?'lab selected':'lab'} key={lab.id}><span className="eyebrow">{lab.id==='secai'?'CSV 기반 재구성':'시연용 가상 데이터'}</span><h2>{lab.name}</h2><p className="muted">{lab.professor}</p><div className="tags">{lab.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><p>{lab.summary}</p><div className="reason">추천 이유: 입력한 관심에서 <strong>{matches.join(', ')}</strong> 태그가 일치해요.</div><small>{source}</small><details><summary>연구 상세보기</summary><p>{lab.problem}</p><p>방법: {lab.methods}</p><p>프로젝트: {lab.project}</p></details><button className={state.selected.includes(lab.id)?'primary':''} onClick={()=>toggleLab(lab.id)}>{state.selected.includes(lab.id)?'✓ 관심 후보 선택됨':'관심 후보 선택'}</button></article>)}</div>}</>}
   {selected.length>0&&<section><h2>선택한 후보 {selected.length}개</h2>{selected.map(l=><label className="field" key={l.id}>{l.name}을 선택한 이유<input value={state.reasons[l.id]||''} onChange={e=>setState(s=>({...invalidate(s,0),reasons:{...s.reasons,[l.id]:e.target.value}}))}/></label>)}<button className="primary" onClick={()=>{complete(0);go(1);}}>선택한 연구실 비교하기 →</button></section>}</>}
   {state.step===1&&<>{selected.length===0?<section className="empty"><p>먼저 비교할 연구실 후보를 선택해 주세요.</p><button onClick={()=>go(0)}>관심 연구실 찾기</button></section>:<><div className="comparison">{selected.map(l=><article key={l.id}><span className="eyebrow">{l.id==='secai'?'CSV 기반 재구성':'시연용 가상 데이터'}</span><h2>{l.name}</h2><p>{l.summary}</p><h3>해결하려는 문제</h3><p>{l.problem}</p><h3>주요 연구 방법</h3><p>{l.methods}</p><details><summary>논문·프로젝트와 후보 차이</summary><p>{l.project}</p>{l.id==='secai'&&<p>{experience.paper}</p>}<p>이 후보는 {l.methods}에 초점을 둡니다. 다른 후보의 문제와 방법을 나란히 비교해 보세요.</p><small>{source}</small></details><button onClick={()=>send('선택한 연구실은 어떤 차이가 있어?')}>도우미에게 차이 물어보기 ↗</button><h3>① 교수님 담당 수업</h3>{courses.filter(c=>c.labId===l.id&&c.kind==='taught').map(courseCard)}<h3>② 연구 이해에 도움 되는 관련 과목</h3>{courses.filter(c=>c.labId===l.id&&c.kind==='related').map(courseCard)}{l.experience===experience.id?<button className="primary" onClick={()=>go(2)}>이 분야 체험하기 →</button>:<div className="notice">이 분야 체험은 준비 중입니다.</div>}</article>)}</div><div className="footer-actions"><button className="primary" onClick={()=>{complete(1);if(selected.some(l=>l.experience))go(2);else go(3);}}>{steps[1].button} →</button></div></>}</>}
   {state.step===2&&<>{!selected.some(l=>l.experience===experience.id)?<section className="empty"><h2>선택한 분야의 체험은 준비 중입니다.</h2><p>현재 체험은 SecAI Lab(구형준)에 연결되어 있습니다.</p><button onClick={()=>go(1)}>후보·수업으로 돌아가기</button><button onClick={()=>go(3)}>체험 없이 준비 정리하기</button></section>:<><section><span className="eyebrow">UNDERGRAD TASK 01</span><h2>{experience.title}</h2><p>{experience.question}</p><div className="task-list">{experience.tasks.map((name,i)=><span key={name} className={task===i?'now':''}>{i+1}. {name}</span>)}</div>
   {task===0&&<><p>선배가 첫 주에 시키는 일입니다. 연구실이 다루는 분야를 하나씩 열고, 각 분야에서 무엇을 보는지 확인합니다.</p><ol className="task-steps">{areas.map(area=><li key={area.id}>{area.name}</li>)}</ol><p className="muted">{experience.disclaimer}</p><button className="primary" onClick={()=>setTask(1)}>분야 열기</button></>}
   {task===1&&(()=>{const area=areas[areaIndex];const on=curious.includes(area.id);return <article className="label-card"><span className="eyebrow">분야 {areaIndex+1} / {areas.length}</span><h3>{area.name}</h3><h3>연구실이 보는 것</h3><p>{area.about}</p><h3>처음 해 보는 일</h3><p>{area.scene}</p><h3>이 분야의 질문</h3><p>{area.question}</p><div className="footer-actions"><button className={on?'primary':''} onClick={()=>setCurious(list=>on?list.filter(id=>id!==area.id):[...list,area.id])}>{on?'✓ 더 궁금함':'이 분야가 더 궁금해요'}</button>{areaIndex>0&&<button onClick={()=>setAreaIndex(areaIndex-1)}>이전 분야</button>}<button className="primary" onClick={()=>{if(areaIndex<areas.length-1)setAreaIndex(areaIndex+1);else setTask(2);}}>{areaIndex<areas.length-1?'다음 분야':'관심 분야 정하기'}</button></div></article>;})()}
   {task===2&&ragOpen&&<RagReview onBack={()=>setRagOpen(false)} onNotice={setNotice}/>}
   {task===2&&!ragOpen&&<><p>일곱 분야를 모두 열었습니다. 더 알고 싶은 분야를 하나 고르세요.</p><div className="chips">{areas.map(area=><button key={area.id} className={focus===area.id?'primary':''} onClick={()=>setFocus(area.id)}>{area.name}{curious.includes(area.id)?' · 궁금':''}</button>)}</div><label className="field">이 분야가 더 궁금한 이유<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="예: AI 보안은 모델이 어떤 자료를 함께 보는지부터 적는 일이 연구처럼 느껴졌다."/></label><label className="field">랩미팅에서 물어볼 질문<textarea value={ask} onChange={e=>setAsk(e.target.value)} placeholder="예: 이상 탐지에서는 평소 기록을 어디까지 모아 두나요?"/></label>{loadRag().committed&&<p className="muted">검색 결과 점검을 저장해 두었습니다. 체험해보기를 다시 열면 이어서 볼 수 있습니다.</p>}<div className="footer-actions"><button className="primary" disabled={!focus||!note.trim()||!ask.trim()} onClick={saveExperiment}>{steps[2].button}</button><button disabled={!focus||!note.trim()||!ask.trim()} onClick={()=>setRagOpen(true)}>체험해보기</button></div></>}</section><button onClick={()=>go(3)}>내 선택과 준비 정리하기 →</button></>}
   <section><h2>저장한 체험 {state.experiments.length}개</h2>{state.experiments.length===0?<p className="muted">아직 저장한 체험이 없습니다.</p>:state.experiments.map(e=>{const picked=areas.find(a=>a.id===e.focus);return <details key={e.id}><summary>{e.date} · {picked?.name}</summary><p>궁금하다고 표시: {e.visits.filter(v=>v.curious).map(v=>areas.find(a=>a.id===v.areaId)?.name).join(', ')||'없음'}</p><p>이유: {e.note}</p><p>질문: {e.ask}</p><button onClick={()=>{setCurious(e.visits.filter(v=>v.curious).map(v=>v.areaId));setFocus(e.focus);setNote(e.note);setAsk(e.ask);setTask(2);setAreaIndex(areas.length-1);}}>당시 선택 불러오기</button></details>;})}</section></>}
   {state.step===3&&<><section><h2>지금까지의 탐색</h2><p>관심: {state.interest||'미입력'}</p><p>후보: {selected.map(l=>l.name).join(', ')||'더 탐색 중'}</p><p>관심 과목: {courses.filter(c=>state.courseIds.includes(c.id)).map(c=>c.name).join(', ')||'없음'}</p><p>저장한 체험: {state.experiments.length}개</p><small>짧은 체험으로 적성이나 연구 능력을 판단하지 않습니다. 최종 후보를 고르지 않아도 괜찮아요.</small></section><section>{reflectionFields.map(([id,label])=><label className="field" key={id}>{label}<textarea value={state.reflection[id]||''} onChange={e=>setState(s=>({...s,reflection:{...s.reflection,[id]:e.target.value},statuses:s.statuses.map((v,i)=>i===3?'진행 중':v)}))}/></label>)}<div className="chips">{['관련 과목 알아보기','입문 자료 읽기','작은 프로젝트 해보기','연구실에 물어볼 질문 정리하기','더 탐색하기'].map(t=><button key={t} onClick={()=>setState(s=>({...s,reflection:{...s.reflection,next:t},statuses:s.statuses.map((v,i)=>i===3?'진행 중':v)}))}>{t}</button>)}</div><button className="primary" disabled={!state.reflection.next?.trim()} onClick={()=>{complete(3);setNotice('준비 기록을 저장했습니다. 언제든 돌아와 수정할 수 있어요.');}}>{steps[3].button}</button></section><div className="footer-actions"><button onClick={async()=>{try{await navigator.clipboard.writeText(summary());setNotice('요약을 복사했습니다.');}catch{setNotice('복사할 수 없습니다. Markdown 다운로드를 이용하세요.');}}}>요약 복사</button><button onClick={()=>{const url=URL.createObjectURL(new Blob([summary()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='나의-연구실-탐색.md';a.click();URL.revokeObjectURL(url);}}>Markdown 다운로드 ↓</button><button onClick={()=>go(0)}>더 탐색하기 →</button></div></>}
   </>}
   <footer><span>연구를 고르는 첫걸음, 나의 속도로.</span><button className="text-button" onClick={()=>{if(window.confirm('관심, 후보, 체험과 채팅을 포함한 모든 기록을 초기화할까요?')){setState(fresh());resetTask();setNotice('모든 탐색 기록을 초기화했습니다.');}}}>전체 기록 초기화</button></footer>
  </main>{chatOpen&&<aside><div className="chat-heading"><span className="assistant-icon">✦</span><div><h2>탐색 도우미</h2><small>데모 응답 · 외부 검색 없음</small></div><button aria-label="도우미 닫기" onClick={()=>setChatOpen(false)}>×</button></div><div className="chat-messages" aria-live="polite"><div className="bubble assistant">안녕하세요! 관심 분야부터 준비 계획까지 함께 정리해요. 아래 예시 질문을 눌러 보세요.</div>{state.messages.map((m,i)=><div className={'bubble '+m.role} key={i}>{m.text}</div>)}{busy&&<p>데모 응답을 준비하고 있어요…</p>}</div><div className="chat-suggestions">{questions[state.step].map(q=><button key={q} disabled={busy} onClick={()=>send(q)}>{q} ↗</button>)}</div><form onSubmit={e=>{e.preventDefault();send(chatInput);}}><label className="sr-only" htmlFor="chat-input">도우미에게 질문</label><input id="chat-input" value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="궁금한 점을 물어보세요"/><button disabled={busy||!chatInput.trim()} type="submit">보내기</button></form><small className="chat-footnote">답변은 데모 자료와 저장한 기록을 사용합니다.</small></aside>}</div>
 </>;
 function courseCard(c:typeof courses[number]){return <div className="course" key={c.id}><strong>{c.name}</strong><small>{c.term} · {c.labId==='secai'?'CSV 기반 재구성':'시연용 가상 데이터'}</small><p>학습: {c.learning}</p><p>{c.connection}</p><button onClick={()=>setState(s=>({...s,courseIds:s.courseIds.includes(c.id)?s.courseIds.filter(id=>id!==c.id):[...s.courseIds,c.id],statuses:s.statuses.map((v,i)=>i===1?'진행 중':i===3&&v!=='시작 전'?'재검토 필요':v)}))}>{state.courseIds.includes(c.id)?'✓ 관심 과목 저장됨':'관심 과목 저장'}</button></div>;}
}
const reflectionFields=[['interesting','체험에서 흥미로웠던 부분'],['difficult','어려웠던 부분'],['question','더 알아보고 싶은 질문'],['reason','현재 관심 연구실과 그 이유 · 체험 후 생각이 달라진 이유'],['uncertain','아직 판단하지 못한 부분'],['next','다음에 할 행동']];
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
